# Generated by Django 2.1.1 on 2018-12-18 18:16

from django.db import migrations, models
import sample_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0004_auto_20181212_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='popularity',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[sample_app.models.validate_even]),
        ),
    ]
